export const insertDataQuery = `

INSERT INTO agjlugar (nombre,tipo) values('RIO DE JANEIRO','ESTADO');
INSERT INTO agjlugar (nombre,tipo) values('SAO PAULO','ESTADO');
INSERT INTO agjlugar (nombre,tipo) values('RIO GRANDE DEL SUR','ESTADO');
INSERT INTO agjlugar (nombre,tipo) values('PERNAMBUCO','ESTADO');
INSERT INTO agjlugar (nombre,tipo) values('MARANHAO','ESTADO');
INSERT INTO agjlugar (nombre,tipo,id_lugar_padre) values('RIO DE JANEIRO','CIUDAD',(SELECT l.id FROM agjlugar l where nombre='RIO DE JANEIRO' AND tipo='ESTADO'));
INSERT INTO agjlugar (nombre,tipo,id_lugar_padre) values('SAO PAULO','CIUDAD',(SELECT l.id FROM agjlugar l where nombre='SAO PAULO' AND tipo='ESTADO'));
INSERT INTO agjlugar (nombre,tipo,id_lugar_padre) values('PORTO ALEGRE','CIUDAD',(SELECT l.id FROM agjlugar l where nombre='RIO GRANDE DEL SUR' AND tipo='ESTADO'));
INSERT INTO agjlugar (nombre,tipo,id_lugar_padre) values('RECIFE','CIUDAD',(SELECT l.id FROM agjlugar l where nombre='PERNAMBUCO' AND tipo='ESTADO'));
INSERT INTO agjlugar (nombre,tipo,id_lugar_padre) values('SAO LUIS','CIUDAD',(SELECT l.id FROM agjlugar l where nombre='MARANHAO' AND tipo='ESTADO'));
INSERT INTO agjlugar (nombre,tipo,id_lugar_padre) values('BELFORD ROXO','CIUDAD',(SELECT l.id FROM agjlugar l where nombre='RIO DE JANEIRO' AND tipo='ESTADO'));
INSERT INTO agjlugar (nombre,tipo) values('PARA','ESTADO');
INSERT INTO agjlugar (nombre,tipo,id_lugar_padre) values('BELEM','CIUDAD',(SELECT l.id FROM agjlugar l where nombre='PARA' AND tipo='ESTADO'));


INSERT INTO agjcolor (nombre) VALUES ('AZUL'), ('AMARILLO'), ('ROJO'), ('BLANCO'), ('VERDE'), ('ROSA'), ('PLATEADO'), ('NEGRO');


INSERT INTO agjescuela_samba (nombre, direccion_sede, resumen_hist, id_lugar) VALUES(
'UNIDOS DA TIJUCA',
'AV. FRANCISCO BICALHO, 47 - SANTO CRISTO',
'LA ESCUELA DE SAMBA UNIDOS DA TIJUCA ES UNA DE LAS MÁS ANTIGUAS DE RIO DE JANEIRO, CON ORÍGENES EN LA DECADA DE 1930. FUE FUNDADA EL 31 DE DICIEMBRE DE 1931 A PARTIR DE LA FUSIÓN DE BLOQUES EXISTENTES EN MORRO DO BOREL. GANO SU PRIMER CARNAVAL CUANDO TENIA CINCO AÑOS, EN 1936, CON EL ENREDO “SONHOS DELIRANTES”. PAULO BARROS ES RESPONSABLE DEL ESTILO INNOVADOR DE LA ESCUELA.',
(SELECT l.id FROM agjlugar l WHERE nombre='RIO DE JANEIRO' AND tipo='CIUDAD'));

INSERT INTO agjescuela_samba (nombre, direccion_sede, resumen_hist, id_lugar) VALUES(
'TOM MAIOR',
'R. SERGIO TOMAS, 622 - BARRA FUNDA',
'EL GREMIO RECREATIVO ESCUELA DE SAMBA TOM MAIOR ES UNA ESCUELA DE SAMBA DE LA CIUDAD DE SAO PAULO. FUE FUNDADA EL 14 DE FEBRERO DE 1973 POR HELIO BAGUNÇA, QUIEN FUE EL PRIMER PRESIDENTE DE LA ESCUELA, JUNTO CON SAMBISTAS TRADICIONALES DE LA CAMISA VERDE E BRANCO 1. SU NOMBRE FUE INSPIRADO EN LOS VERSOS DE LA CANCIÓN DE MARTINHO DA VILA: “VAI TER DE AMAR A LIBERDADE, SO VAI CANTAR EM TOM MAIOR, VAI TER A FELICIDADE DE VER UM BRASIL MELHOR…” ',
(SELECT l.id FROM agjlugar l WHERE nombre='SAO PAULO' AND tipo='CIUDAD'));

INSERT INTO agjescuela_samba (nombre, direccion_sede, resumen_hist, id_lugar) VALUES(
'IMPERIO DA ZONA NORTE',
'AV. SERTORIO, 1021 - NAVEGANTES',
'FUE FUNDADA EL 20 DE MARZO DE 1975 POR PEDRO GUILHERME LOPES, WALDIR ALVES, OSCAR ALVES, HEITOR LOPES, CARLOS ALBERTO, GILDO LOPES Y ANA REGINA LOPES 1. INICIALMENTE UBICADA EN EL BARRIO SARANDI, LA ESCUELA ACABO MUDANDOSE A OTRO BARRIO EN LA ZONA NORTE, EL NAVEGANTES, DONDE TIENE SU CUADRA EN LA AVENIDA SERTORIO 1. DESPUES DE GANAR EL CARNAVAL DE 1982, LA ESCUELA ACABO PASANDO POR MALOS MOMENTOS A FINALES DE LA DECADA DE 1990. DESPUES DE CONSEGUIR RESTABLECERSE Y SUBIR AL GRUPO ESPECIAL NUEVAMENTE EN 2005, BAJO EL MANDO DE ANTONIO ADEMIR MORAES (EL OSO), EL IMPERIO FUE VICECAMPEON EN 2006 Y 2007.',
(SELECT l.id FROM agjlugar l WHERE nombre='PORTO ALEGRE' AND tipo='CIUDAD'));

INSERT INTO agjescuela_samba (nombre, direccion_sede, resumen_hist, id_lugar) VALUES(
'MANGUEIRA DO AMANHA',
'RUA VISCONDE DE NITEROI, 1072, MANGUEIRA',
'LA MANGUEIRA DO AMANHA ES UNO DE LOS PROYECTOS SOCIALES DE LA GRES ESTAÇAO PRIMEIRA DE MANGUEIRA. UNA DE SUS FUNDADORAS ES LA CANTANTE ALCIONE, ACTUALMENTE SU PRESIDENTA DE HONRA. EN LA FECHA DE CREACION, EN 1987, LA CANTANTE MARIA BETHANIA SIRVIO DE MADRINA DE LA ESCUELA. LA AGRUPACION CUENTA CON LA PARTICIPACION DE NIÑOS Y ADOLESCENTES ENTRE 7 Y 17 AÑOS. LA MANGUEIRA DO AMANHA YA HA TENIDO MAS DE 3.000 COMPONENTES DESFILANDO EN EL MISMO AÑO Y YA HA REVELADO VARIOS TALENTOS Y ARTISTAS QUE HOY FOFORMAN PARTE DE LA ESCUELA PRINCIPAL.',
(SELECT l.id FROM agjlugar l WHERE nombre='RIO DE JANEIRO' AND tipo='CIUDAD'));

INSERT INTO agjescuela_samba (nombre, direccion_sede, resumen_hist, id_lugar) VALUES(
'UNIDOS DE SAO MIGUEL',
'R. MESQUITA - PADRE MIGUEL',
'EL GREMIO RECREATIVO ESCUELA DE SAMBA UNIDOS DE PADRE MIGUEL ES UNA ESCUELA DE SAMBA DE LA CIUDAD DE RIO DE JANEIRO FUNDADA EL DIA 12 DE NOVIEMBRE DE 1957 1. ESTA UBICADA EN LA CALLE MEZQUITA EN VILA VINTEM, EN EL BARRIO DE PADRE MIGUEL. EL INICIO DE LA ESCUELA FUE BRILLANTE, PUES INMEDIATAMENTE EN SU PRIMER DESFILE EN LA PLAZA ONCE EN 1959 SE CONSAGRO CAMPEONA Y ADQUIRIO EL DERECHO DE PRESENTARSE ENTRE LAS GRANDES EN 1960. SIN EMBARGO, LA MALA COLOCACION QUE OBTUVO, LA HIZO REGRESAR A LAS CATEGORIAS INFERIORES. LA ESCUELA VOLVIO A DESFILAR ENTRE LAS GRANDES EN 1964, 1971 Y 1972.',
(SELECT l.id FROM agjlugar l WHERE nombre='RIO DE JANEIRO' AND tipo='CIUDAD'));

INSERT INTO agjescuela_samba (nombre, direccion_sede, resumen_hist, id_lugar) VALUES(
'IMPERIO PEDREIRENSE',
'TV. MAURITI, 1135 - PEDREIRA',
'FUE FUNDADA EL 6 DE DICIEMBRE DE 1951, EN EL BARRIO DE PEDREIRA, COMO LA ESCUELA DE SAMBA “MARACATU DO SUBURBIO” 1. DESDE SU PRIMER CARNAVAL EN 1952 (DESFILO CON EL ENREDO “O LARGO DA POLVORA”), SIEMPRE MANTUVO GRANDES DESTAQUES HASTA 1958. FUERON 7 AÑOS DE GLORIAS PARA EL BARRIO, OBTENIENDO VARIOS TITULOS, INCLUSO EL DE CAMPEONA. UNO DE SUS FUNDADORES FUE PAULO ROBERTO, QUIEN SE COMPROMETIO A DAR EL TITULO DEL CARNAVAL PARA LA ESCUELA. UNA DE LAS PRIMERAS MEDIDAS ADMINISTRATIVAS QUE TOMO FUE CONVENCER A SU DIRECTIVA A CAMBIAR EL NOMBRE DE LA ESCUELA, PUES LA EXPRESION “DO SUBÚRBIO” ERA PEYORATIVA Y PRESENTÓ LA PROPUESTA DE LOS ESTATUTOS DE LA “EMBAIXADA DE SAMBA DO IMPERIO PEDREIRENSE”, QUE FUE APROBADA EN 1958, VIGORANDO HASTA ESTA FECHA',
(SELECT l.id FROM agjlugar l WHERE nombre='BELEM' AND tipo='CIUDAD'));

INSERT INTO agjescuela_samba (nombre, direccion_sede, resumen_hist, id_lugar) VALUES(
'UNIDOS DA BANGU',
'R. FRANCISCO REAL, 1445 - BANGU',
'EL GREMIO RECREATIVO ESCUELA DE SAMBA UNIDOS DE BANGU ES UNA ESCUELA DE SAMBA DE LA CIUDAD DE RIO DE JANEIRO, CON SEDE EN EL BARRIO DE BANGU. FUE FUNDADA EL 15 DE NOVIEMBRE DE 1937 Y SUS PRIMERAS COLORES OFICIALES FUERON AZUL Y BLANCO. SOLO ADOPTO SUS COLORES ORIGINALES, ROJO Y BLANCO, EN 1966, EN HOMENAJE AL SEGUNDO TÍTULO DEL CAMPEONATO CARIOCA CONQUISTADO POR EL BANGU ATLETICO CLUBE',
(SELECT l.id FROM agjlugar l WHERE nombre='RIO DE JANEIRO' AND tipo='CIUDAD'));

INSERT INTO agjescuela_samba (nombre, direccion_sede, resumen_hist, id_lugar) VALUES(
'INOCENTES DE BELFORD ROXO',
'BLVD. SAO VICENTE, 1741 - PARQUE SAO VICENTE',
'EL GRES INOCENTES DE BELFORD ROXO ES UNA DE LAS MAS NUEVAS ASOCIACIONES DEL CARNAVAL CARIOCA, FUNDADA EL 11 DE JULIO DE 1993. LA ESCUELA SUCEDIO A UNIDOS DA MATRIZ Y TIENE ENTRE SUS FUNDADORES A LUIZ DE BASTOS, SEBASTIÃO QUIRINO, JAIRO DA SILVA, ARISTOTELINA DE OLIVEIRA, ABILIO DEL REY, WALTER SARDINHA, ENTRE OTROS',
(SELECT l.id FROM agjlugar l WHERE nombre='BELFORD ROXO' AND tipo='CIUDAD'));

INSERT INTO agjescuela_samba (nombre, direccion_sede, resumen_hist, id_lugar) VALUES(
'IMPERIO DA TIJUCA',
'R. MEDEIROS PASSARO, 84 - TIJUCA',
'LA ESCUELA DE SAMBA IMPERIO DA TIJUCA FUE FUNDADA EN 1940, EN EL MORRO DA FORMIGA, UBICADO EN EL BARRIO DE TIJUCA, A PARTIR DE LA FUSION ENTRE LAS ANTIGUAS ESCUELAS RECREIO DA MOCIDADE Y ESTRELA DA TIJUCA. FUE LA PRIMERA ESCUELA DE SAMBA EN USAR EN SU NOMBRE EL TERMINO “IMPERIO”, RAZON POR LA CUAL TIENE UNA CORONA, SÍMBOLO DE LA NOBLEZA, EN SU BANDERA, ASI COMO RAMOS DE FUMO Y CAFE QUE TRADUCIAN LAS RIQUEZAS DEL BRASIL EN LA EPOCA',
(SELECT l.id FROM agjlugar l WHERE nombre='RIO DE JANEIRO' AND tipo='CIUDAD'));

INSERT INTO agjpatrocinante_empresa (nombre, email_contacto, mision)
VALUES
('NIKE', 'EVENTS@NIKE.COM', 'OFRECER INSPIRACION E INNOVACION A TODOS LOS ATLETAS DEL MUNDO'),
('PROCTER & GAMBLE', 'CONTACT@P&G.COM', 'OFRECEMOS PRODUCTOS Y SERVICIOS DE MARCA DE UNA CALIDAD Y VALOR SUPERIOR'),
('UNICEF','BRAZIL@UNICEF.ORG', 'PROMUEVE LOS DERECHOS Y EL BIENESTAR DE TODOS LOS NIÑOS Y NIÑAS, EN TODO LO QUE HACEMOS'),
('PEPSI','CONSUMIDORES.55@PEPSICO.COM', 'BRINDAR A LOS CONSUMIDORES ALIMENTOS Y BEBIDAS DELICIOSOS, ASEQUIBLES, PRACTICOS Y COMPLEMENTARIOS'),
('B3','NEGOCIACAO@B3.COM.BR ', 'IMPULSAR EL CRECIMIENTO DE BRASIL JUNTO CON SUS CLIENTES Y LA SOCIEDAD'),
('RE/MAX','GERENCIA@ORION.REMAX.COM.BR', 'SER LOS LIDERES MUNDIALES EN BIENES RAICES, ALCANZANDO NUESTRAS METAS AYUDANDO A OTROS ALCANZAR LAS SUYAS'),
('GRUPO MODELO','CONTACTO@GMODELO.COM.MX', 'IMPLEMENTAR LAS MEJORES PRACTICAS EN HERRAMIENTAS Y TECNICAS, ESTABLECIENDO LOS COMPORTAMIENTOS NECESARIOS PARA MANTENER LA CULTURA DE LA MEJORA CONTINUA'),
('MARSHALL AMPLIFICATION','CONTACTUS@MARSHALL.COM', 'INNOVAR Y EMPUJAR LAS BARRERAS DE POSIBILIDAD PARA INSPIRAR A TODOS A CONSEGUIR SU SONIDO'),
('UNITED HEALTH GROUP','SUSTAINABILITY@UHG.COM', 'AYUDAR A LAS PERSONAS A VIVIR VIDAS MAS SALUDABLES Y PROMOVER UN SISTEMA DE SALUD UE FUNCIONE MEJOR PARA TODOS');

INSERT INTO agjpatrocinante_persona (primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, doc_identidad, email_contacto) 
VALUES
('PEDRO', 'EDUARDO', 'PEREZ', 'IZAGUIRRE', '6911502', 'PEDRO@GMAIL.COM'),
('LUISA', 'MARTA', 'RODRIGUEZ', 'LOINAZ', '10335089', 'LUISA_RO@GMAIL.COM'),
('LUIS', NULL, 'TERRERO', 'TORRES', '28308949', 'JDTERRE@GMAIL.COM'),
('MARIA', 'VALENTINA', 'GIL', 'BLANCO', '29658784', 'MVGIL@GMAIL.COM'),
('VALENTINA', 'MARGARITA', 'CABRERA', 'GIMENEZ', '30986332', 'VCABRA25@GMAIL.COM');
`;

// INSERT INTO agje_c(agjescuela_samba_id,agjcolor_id) VALUES(
//     (SELECT e.id FROM agjescuela_samba e WHERE nombre='UNIDOS DA TIJUCA'),
//     (SELECT c.id FROM agjcolor c WHERE nombre='AMARILLO'));
    
//     INSERT INTO agje_c(agjescuela_samba_id,agjcolor_id) VALUES(
//     (SELECT e.id FROM agjescuela_samba e WHERE nombre='UNIDOS DA TIJUCA'),
//     (SELECT c.id FROM agjcolor c WHERE nombre='AZUL'));
    
//     INSERT INTO agje_c(agjescuela_samba_id,agjcolor_id) VALUES(
//     (SELECT e.id FROM agjescuela_samba e WHERE nombre='TOM MAIOR'),
//     (SELECT c.id FROM agjcolor c WHERE nombre='AMARILLO'));
    
//     INSERT INTO agje_c(agjescuela_samba_id,agjcolor_id) VALUES(
//     (SELECT e.id FROM agjescuela_samba e WHERE nombre='TOM MAIOR'),
//     (SELECT c.id FROM agjcolor c WHERE nombre='ROJO'));
    
//     INSERT INTO agje_c(agjescuela_samba_id,agjcolor_id) VALUES(
//     (SELECT e.id FROM agjescuela_samba e WHERE nombre='TOM MAIOR'),
//     (SELECT c.id FROM agjcolor c WHERE nombre='BLANCO'));
    
//     INSERT INTO agje_c(agjescuela_samba_id,agjcolor_id) VALUES(
//     (SELECT e.id FROM agjescuela_samba e WHERE nombre='IMPERIO DA ZONA NORTE'),
//     (SELECT c.id FROM agjcolor c WHERE nombre='BLANCO'));
    
//     INSERT INTO agje_c(agjescuela_samba_id,agjcolor_id) VALUES(
//     (SELECT e.id FROM agjescuela_samba e WHERE nombre='IMPERIO DA ZONA NORTE'),
//     (SELECT c.id FROM agjcolor c WHERE nombre='AMARILLO'));
    
//     INSERT INTO agje_c(agjescuela_samba_id,agjcolor_id) VALUES(
//     (SELECT e.id FROM agjescuela_samba e WHERE nombre='IMPERIO DA ZONA NORTE'),
//     (SELECT c.id FROM agjcolor c WHERE nombre='PLATEADO'));
    
//     INSERT INTO agje_c(agjescuela_samba_id,agjcolor_id) VALUES(
//     (SELECT e.id FROM agjescuela_samba e WHERE nombre='MANGUEIRA DO AMANHA'),
//     (SELECT c.id FROM agjcolor c WHERE nombre='VERDE'));
    
//     INSERT INTO agje_c(agjescuela_samba_id,agjcolor_id) VALUES(
//     (SELECT e.id FROM agjescuela_samba e WHERE nombre='MANGUEIRA DO AMANHA'),
//     (SELECT c.id FROM agjcolor c WHERE nombre='ROSA'));
    
//     INSERT INTO agje_c(agjescuela_samba_id,agjcolor_id) VALUES(
//     (SELECT e.id FROM agjescuela_samba e WHERE nombre='UNIDOS DE SAO MIGUEL'),
//     (SELECT c.id FROM agjcolor c WHERE nombre='ROJO'));
    
//     INSERT INTO agje_c(agjescuela_samba_id,agjcolor_id) VALUES(
//     (SELECT e.id FROM agjescuela_samba e WHERE nombre='UNIDOS DE SAO MIGUEL'),
//     (SELECT c.id FROM agjcolor c WHERE nombre='AMARILLO'));
    
//     INSERT INTO agje_c(agjescuela_samba_id,agjcolor_id) VALUES(
//     (SELECT e.id FROM agjescuela_samba e WHERE nombre='UNIDOS DE SAO MIGUEL'),
//     (SELECT c.id FROM agjcolor c WHERE nombre='BLANCO'));
    
//     INSERT INTO agje_c(agjescuela_samba_id,agjcolor_id) VALUES(
//     (SELECT e.id FROM agjescuela_samba e WHERE nombre='UNIDOS DE SAO MIGUEL'),
//     (SELECT c.id FROM agjcolor c WHERE nombre='NEGRO'));
    
//     INSERT INTO agje_c(agjescuela_samba_id,agjcolor_id) VALUES(
//     (SELECT e.id FROM agjescuela_samba e WHERE nombre='IMPERIO PEDREIRENSE'),
//     (SELECT c.id FROM agjcolor c WHERE nombre='AZUL'));
    
//     INSERT INTO agje_c(agjescuela_samba_id,agjcolor_id) VALUES(
//     (SELECT e.id FROM agjescuela_samba e WHERE nombre='IMPERIO PEDREIRENSE'),
//     (SELECT c.id FROM agjcolor c WHERE nombre='ROJO'));
    
//     INSERT INTO agje_c(agjescuela_samba_id,agjcolor_id) VALUES(
//     (SELECT e.id FROM agjescuela_samba e WHERE nombre='IMPERIO PEDREIRENSE'),
//     (SELECT c.id FROM agjcolor c WHERE nombre='BLANCO'));
    
//     INSERT INTO agje_c(agjescuela_samba_id,agjcolor_id) VALUES(
//     (SELECT e.id FROM agjescuela_samba e WHERE nombre='UNIDOS DA BANGU'),
//     (SELECT c.id FROM agjcolor c WHERE nombre='BLANCO'));
    
//     INSERT INTO agje_c(agjescuela_samba_id,agjcolor_id) VALUES(
//     (SELECT e.id FROM agjescuela_samba e WHERE nombre='UNIDOS DA BANGU'),
//     (SELECT c.id FROM agjcolor c WHERE nombre='ROJO'));
    
//     INSERT INTO agje_c(agjescuela_samba_id,agjcolor_id) VALUES(
//     (SELECT e.id FROM agjescuela_samba e WHERE nombre='INOCENTES DA BELFORD ROXO'),
//     (SELECT c.id FROM agjcolor c WHERE nombre='ROJO'));
    
//     INSERT INTO agje_c(agjescuela_samba_id,agjcolor_id) VALUES(
//     (SELECT e.id FROM agjescuela_samba e WHERE nombre='INOCENTES DA BELFORD ROXO'),
//     (SELECT c.id FROM agjcolor c WHERE nombre='AZUL'));
    
//     INSERT INTO agje_c(agjescuela_samba_id,agjcolor_id) VALUES(
//     (SELECT e.id FROM agjescuela_samba e WHERE nombre='INOCENTES DA BELFORD ROXO'),
//     (SELECT c.id FROM agjcolor c WHERE nombre='BLANCO'));
    
//     INSERT INTO agje_c(agjescuela_samba_id,agjcolor_id) VALUES(
//     (SELECT e.id FROM agjescuela_samba e WHERE nombre='IMPERIO DA TIJUCA'),
//     (SELECT c.id FROM agjcolor c WHERE nombre='BLANCO'));
    
//     INSERT INTO agje_c(agjescuela_samba_id,agjcolor_id) VALUES(
//     (SELECT e.id FROM agjescuela_samba e WHERE nombre='IMPERIO DA TIJUCA'),
//     (SELECT c.id FROM agjcolor c WHERE nombre='VERDE'));